/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-02-26 12:21:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import bean.Provider;
import bean.PileBean;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"bootstrap/bootstrap.min.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form action=\"login.jsp\" style=\"padding-left: 5.2%;padding-top: 5%;\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-lg btn-info\">Login</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 

Class.forName("org.sqlite.JDBC");
Connection conn = DriverManager.getConnection("jdbc:sqlite:D:/Eclipse/db/aes.db");
Statement stat = conn.createStatement();


      out.write("\r\n");
      out.write("<div class=\"page-header\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t<h1>Duterte Precinct Level Totals</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-6\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t<table class=\"table table-striped\">\r\n");
      out.write("    \t<thead>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th>Candidacy</th>\r\n");
      out.write("                <th>Name</th>\r\n");
      out.write("                <th>Votes</th>\r\n");
      out.write("                <th>Level</th>\r\n");
      out.write("                <th>Precinct</th>\r\n");
      out.write("                <th>City</th>\r\n");
      out.write("                <th>District</th>\r\n");
      out.write("                <th>Province</th>\r\n");
      out.write("                <th>Region</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>     \r\n");
      out.write("\t\t\t");

			ResultSet duterte = stat.executeQuery("SELECT * FROM tapat WHERE name='Rodrigo Duterte';");
			while (duterte.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("vote") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("level") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("precinct") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("city") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("district") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("province") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( duterte.getString("region") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			duterte.close();
			
			ResultSet totalduterte = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Rodrigo Duterte';");
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td><strong>TOTAL VOTES</strong></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-decoration: underline;\"><strong> ");
      out.print( totalduterte.getString("TOTALVOTES") );
      out.write(" </strong></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t");
 totalduterte.close(); 
      out.write("\r\n");
      out.write("    \t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"position: absolute; top: 15.5%; left: 50%;\">\r\n");
      out.write("\t<div class=\"page-header\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<h1>Binay Precinct Level Totals</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-6\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t    \t<thead>\r\n");
      out.write("\t              <tr>\r\n");
      out.write("\t                <th>Candidacy</th>\r\n");
      out.write("\t                <th>Name</th>\r\n");
      out.write("\t                <th>Votes</th>\r\n");
      out.write("\t                <th>Level</th>\r\n");
      out.write("\t                <th>Precinct</th>\r\n");
      out.write("\t                <th>City</th>\r\n");
      out.write("\t                <th>District</th>\r\n");
      out.write("\t                <th>Province</th>\r\n");
      out.write("\t                <th>Region</th>\r\n");
      out.write("\t              </tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>     \r\n");
      out.write("\t\t\t\t");

				ResultSet binay = stat.executeQuery("SELECT * FROM tapat WHERE name='Jejomar Binay';");
				while (binay.next()) {	    
				    
      out.write("\r\n");
      out.write("\t\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("vote") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("level") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("precinct") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("city") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("district") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("province") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( binay.getString("region") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t\t    ");

				}
				binay.close();
				
				ResultSet totalbinay = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Jejomar Binay';");
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td><strong>TOTAL VOTES</strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-decoration: underline;\"><strong> ");
      out.print( totalbinay.getString("TOTALVOTES") );
      out.write(" </strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 totalbinay.close(); 
      out.write("\r\n");
      out.write("\t    \t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"position: absolute; top: 90%; left: 3%;\">\r\n");
      out.write("\t<div class=\"page-header\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<h1>Santiago Precinct Level Totals</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-6\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t    \t<thead>\r\n");
      out.write("\t              <tr>\r\n");
      out.write("\t                <th>Candidacy</th>\r\n");
      out.write("\t                <th>Name</th>\r\n");
      out.write("\t                <th>Votes</th>\r\n");
      out.write("\t                <th>Level</th>\r\n");
      out.write("\t                <th>Precinct</th>\r\n");
      out.write("\t                <th>City</th>\r\n");
      out.write("\t                <th>District</th>\r\n");
      out.write("\t                <th>Province</th>\r\n");
      out.write("\t                <th>Region</th>\r\n");
      out.write("\t              </tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>     \r\n");
      out.write("\t\t\t\t");

				ResultSet santiago = stat.executeQuery("SELECT * FROM tapat WHERE name='Miriam Santiago';");
				while (binay.next()) {	    
				    
      out.write("\r\n");
      out.write("\t\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("vote") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("level") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("precinct") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("city") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("district") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("province") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( santiago.getString("region") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t\t    ");

				}
				santiago.close();
				
				ResultSet totalsantiago = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Miriam Santiago';");
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td><strong>TOTAL VOTES</strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-decoration: underline;\"><strong> ");
      out.print( totalsantiago.getString("TOTALVOTES") );
      out.write(" </strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 totalsantiago.close(); 
      out.write("\r\n");
      out.write("\t    \t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"position: absolute; top: 90%; left: 50%;\">\r\n");
      out.write("\t<div class=\"page-header\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<h1>Roxas Precinct Level Totals</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-6\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t    \t<thead>\r\n");
      out.write("\t              <tr>\r\n");
      out.write("\t                <th>Candidacy</th>\r\n");
      out.write("\t                <th>Name</th>\r\n");
      out.write("\t                <th>Votes</th>\r\n");
      out.write("\t                <th>Level</th>\r\n");
      out.write("\t                <th>Precinct</th>\r\n");
      out.write("\t                <th>City</th>\r\n");
      out.write("\t                <th>District</th>\r\n");
      out.write("\t                <th>Province</th>\r\n");
      out.write("\t                <th>Region</th>\r\n");
      out.write("\t              </tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>     \r\n");
      out.write("\t\t\t\t");

				ResultSet roxas = stat.executeQuery("SELECT * FROM tapat WHERE name='Mar Roxas';");
				while (roxas.next()) {	    
				    
      out.write("\r\n");
      out.write("\t\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("vote") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("level") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("precinct") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("city") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("district") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("province") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( roxas.getString("region") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t\t    ");

				}
				roxas.close();
				
				ResultSet totalroxas = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Mar Roxas';");
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td><strong>TOTAL VOTES</strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-decoration: underline;\"><strong> ");
      out.print( totalroxas.getString("TOTALVOTES") );
      out.write(" </strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 totalroxas.close(); 
      out.write("\r\n");
      out.write("\t    \t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"position: absolute; top: 165%; left: 3%;\">\r\n");
      out.write("\t<div class=\"page-header\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<h1>Poe Precinct Level Totals</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-6\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t    \t<thead>\r\n");
      out.write("\t              <tr>\r\n");
      out.write("\t                <th>Candidacy</th>\r\n");
      out.write("\t                <th>Name</th>\r\n");
      out.write("\t                <th>Votes</th>\r\n");
      out.write("\t                <th>Level</th>\r\n");
      out.write("\t                <th>Precinct</th>\r\n");
      out.write("\t                <th>City</th>\r\n");
      out.write("\t                <th>District</th>\r\n");
      out.write("\t                <th>Province</th>\r\n");
      out.write("\t                <th>Region</th>\r\n");
      out.write("\t              </tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>     \r\n");
      out.write("\t\t\t\t");

				ResultSet poe = stat.executeQuery("SELECT * FROM tapat WHERE name='Grace Poe';");
				while (poe.next()) {	    
				    
      out.write("\r\n");
      out.write("\t\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("vote") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("level") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("precinct") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("city") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("district") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("province") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( poe.getString("region") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t\t    ");

				}
				poe.close();
				
				ResultSet totalpoe = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Grace Poe';");
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td><strong>TOTAL VOTES</strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-decoration: underline;\"><strong> ");
      out.print( totalpoe.getString("TOTALVOTES") );
      out.write(" </strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 totalpoe.close(); 
      out.write("\r\n");
      out.write("\t    \t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"position: absolute; top: 165%; left: 50%;\">\r\n");
      out.write("\t<div class=\"page-header\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<h1>Seneres Precinct Level Totals</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-6\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t    \t<thead>\r\n");
      out.write("\t              <tr>\r\n");
      out.write("\t                <th>Candidacy</th>\r\n");
      out.write("\t                <th>Name</th>\r\n");
      out.write("\t                <th>Votes</th>\r\n");
      out.write("\t                <th>Level</th>\r\n");
      out.write("\t                <th>Precinct</th>\r\n");
      out.write("\t                <th>City</th>\r\n");
      out.write("\t                <th>District</th>\r\n");
      out.write("\t                <th>Province</th>\r\n");
      out.write("\t                <th>Region</th>\r\n");
      out.write("\t              </tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>     \r\n");
      out.write("\t\t\t\t");

				ResultSet seneres = stat.executeQuery("SELECT * FROM tapat WHERE name='Roy Seneres';");
				while (seneres.next()) {	    
				    
      out.write("\r\n");
      out.write("\t\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("vote") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("level") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("precinct") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("city") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("district") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("province") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t\t<td>");
      out.print( seneres.getString("region") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t\t    ");

				}
				seneres.close();
				
				ResultSet totalseneres = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Roy Seneres';");
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td><strong>TOTAL VOTES</strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-decoration: underline;\"><strong> ");
      out.print( totalseneres.getString("TOTALVOTES") );
      out.write(" </strong></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 totalseneres.close(); 
      out.write("\r\n");
      out.write("\t    \t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
	stat.close();
	conn.close();	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
