/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-03-11 20:36:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"bootstrap/bootstrap.min.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\r\n");
      out.write("<title>AES - Index</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	Class.forName("org.sqlite.JDBC");
	Connection conn = DriverManager.getConnection("jdbc:sqlite:D:/Eclipse/db/aes.db");
	Statement stat = conn.createStatement();

      out.write("\r\n");
      out.write("<div class=\"page-header\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t<h1>Region: NCR</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-6\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t<table class=\"table table-striped\">\r\n");
      out.write("    \t<thead>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th>Candidacy</th>\r\n");
      out.write("                <th>Candidate</th>\r\n");
      out.write("                <th>Votes</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>     \r\n");
      out.write("\t\t\t");

			ResultSet totalduterte = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Rodrigo Duterte';");
			String dutertetotal = totalduterte.getString("TOTALVOTES");
			totalduterte.close();
			
			ResultSet regionNCRduterte = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Rodrigo Duterte';");
			while (regionNCRduterte.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRduterte.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRduterte.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( dutertetotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRduterte.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalbinay = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Jejomar Binay';");
			String binaytotal = totalbinay.getString("TOTALVOTES");
			totalbinay.close();
			
			ResultSet regionNCRbinay = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Jejomar Binay';");
			while (regionNCRbinay.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbinay.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbinay.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( binaytotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRbinay.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalsantiago = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Miriam Santiago';");
			String santiagototal = totalsantiago.getString("TOTALVOTES");
			totalsantiago.close();
			
			ResultSet regionNCRsantiago = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Miriam Santiago';");
			while (regionNCRsantiago.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRsantiago.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRsantiago.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( santiagototal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRsantiago.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalpoe = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Grace Poe';");
			String poetotal = totalpoe.getString("TOTALVOTES");
			totalpoe.close();
			
			ResultSet regionNCRpoe = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Grace Poe';");
			while (regionNCRpoe.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRpoe.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRpoe.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( poetotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRpoe.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalroxas = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Mar Roxas';");
			String roxastotal = totalroxas.getString("TOTALVOTES");
			totalroxas.close();
			
			ResultSet regionNCRroxas = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Mar Roxas';");
			while (regionNCRroxas.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRroxas.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRroxas.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( roxastotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRroxas.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalhonasan = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Gringo Honasan';");
			String honasantotal = totalhonasan.getString("TOTALVOTES");
			totalhonasan.close();
			
			ResultSet regionNCRhonasan = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Gringo Honasan';");
			while (regionNCRhonasan.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRhonasan.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRhonasan.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( honasantotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRhonasan.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totaltrillanes = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Antonio Trillanes';");
			String trillanestotal = totaltrillanes.getString("TOTALVOTES");
			totaltrillanes.close();
			
			ResultSet regionNCRtrillanes = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Antonio Trillanes';");
			while (regionNCRtrillanes.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRtrillanes.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRtrillanes.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( trillanestotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRtrillanes.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalescudero = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Francis Escudero';");
			String escuderototal = totalescudero.getString("TOTALVOTES");
			totalescudero.close();
			
			ResultSet regionNCRescudero = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Francis Escudero';");
			while (regionNCRescudero.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRescudero.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRescudero.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( escuderototal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRescudero.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalrobredo = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Leni Robredo';");
			String robredototal = totalrobredo.getString("TOTALVOTES");
			totalrobredo.close();
			
			ResultSet regionNCRrobredo = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Leni Robredo';");
			while (regionNCRrobredo.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRrobredo.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRrobredo.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( robredototal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRrobredo.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalmarcos = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Bongbong Marcos';");
			String marcostotal = totalmarcos.getString("TOTALVOTES");
			totalmarcos.close();
			
			ResultSet regionNCRmarcos = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Bongbong Marcos';");
			while (regionNCRmarcos.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRmarcos.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRmarcos.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( marcostotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRmarcos.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalalan = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Alan Peter Cayetano';");
			String alantotal = totalalan.getString("TOTALVOTES");
			totalalan.close();
			
			ResultSet regionNCRalan = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Alan Peter Cayetano';");
			while (regionNCRmarcos.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRalan.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRalan.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( alantotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRalan.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalshariff = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Shariff Albani';");
			String sharifftotal = totalshariff.getString("TOTALVOTES");
			totalshariff.close();
			
			ResultSet regionNCRshariff = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Shariff Albani';");
			while (regionNCRshariff.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRshariff.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRshariff.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( sharifftotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRshariff.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalaldin = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Aldin Ali';");
			String aldintotal = totalaldin.getString("TOTALVOTES");
			totalaldin.close();
			
			ResultSet regionNCRaldin = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Aldin Ali';");
			while (regionNCRaldin.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRaldin.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRaldin.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( aldintotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRaldin.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalalunan = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Alunan Raffy';");
			String alunantotal = totalalunan.getString("TOTALVOTES");
			totalalunan.close();
			
			ResultSet regionNCRalunan = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Alunan Raffy';");
			while (regionNCRalunan.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRalunan.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRalunan.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( alunantotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRalunan.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalambolodto = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Ambolodto Ina';");
			String ambolodtototal = totalambolodto.getString("TOTALVOTES");
			totalambolodto.close();
			
			ResultSet regionNCRambolodto = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Ambolodto Ina';");
			while (regionNCRambolodto.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRambolodto.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRambolodto.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( ambolodtototal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRambolodto.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalarquiza = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Godofredo Arquiza';");
			String arquizatotal = totalarquiza.getString("TOTALVOTES");
			totalarquiza.close();
			
			ResultSet regionNCRarquiza = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Godofredo Arquiza';");
			while (regionNCRarquiza.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRarquiza.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRarquiza.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( arquizatotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRarquiza.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalbaligod = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Levito Baligod';");
			String baligodtotal = totalbaligod.getString("TOTALVOTES");
			totalbaligod.close();
			
			ResultSet regionNCRbaligod = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Levito Baligod';");
			while (regionNCRbaligod.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbaligod.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbaligod.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( baligodtotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRbaligod.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalbello = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Bello Walden';");
			String bellototal = totalbello.getString("TOTALVOTES");
			totalbello.close();
			
			ResultSet regionNCRbello = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Bello Walden';");
			while (regionNCRbello.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbello.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbello.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( bellototal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRbello.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalcam = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Cam Sandra';");
			String camtotal = totalcam.getString("TOTALVOTES");
			totalcam.close();
			
			ResultSet regionNCRcam = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Cam Sandra';");
			while (regionNCRcam.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRcam.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRcam.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( camtotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRcam.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalnel = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Chavez Nel';");
			String neltotal = totalnel.getString("TOTALVOTES");
			totalnel.close();
			
			ResultSet regionNCRnel = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Chavez Nel';");
			while (regionNCRnel.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRnel.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRnel.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( neltotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRnel.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalneri = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Colmenares Neri';");
			String neritotal = totalneri.getString("TOTALVOTES");
			totalneri.close();
			
			ResultSet regionNCRneri = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Colmenares Neri';");
			while (regionNCRneri.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRneri.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRneri.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( neritotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRneri.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalleila = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='De Lima Leila';");
			String leilatotal = totalleila.getString("TOTALVOTES");
			totalleila.close();
			
			ResultSet regionNCRleila = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='De Lima Leila';");
			while (regionNCRleila.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRleila.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRleila.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( leilatotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRleila.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalisko = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Domagoso Isko Moreno';");
			String iskototal = totalisko.getString("TOTALVOTES");
			totalisko.close();
			
			ResultSet regionNCRisko = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Domagoso Isko Moreno';");
			while (regionNCRisko.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRisko.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRisko.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( iskototal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRisko.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totaldorona = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Dorona Ray';");
			String doronatotal = totaldorona.getString("TOTALVOTES");
			totaldorona.close();
			
			ResultSet regionNCRdorona = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Dorona Ray';");
			while (regionNCRdorona.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdorona.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdorona.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( doronatotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRdorona.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totaldrilon = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Drilon Frank';");
			String drilontotal = totaldrilon.getString("TOTALVOTES");
			totaldrilon.close();
			
			ResultSet regionNCRdrilon = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Drilon Frank';");
			while (regionNCRdorona.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdrilon.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdrilon.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( drilontotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRdrilon.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalgadon = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Gadon Larry';");
			String gadontotal = totalgadon.getString("TOTALVOTES");
			totalgadon.close();
			
			ResultSet regionNCRgadon = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Gadon Larry';");
			while (regionNCRgadon.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRgadon.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRgadon.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( gadontotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRgadon.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalwin = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Gatchalian Win';");
			String wintotal = totalwin.getString("TOTALVOTES");
			totalwin.close();
			
			ResultSet regionNCRwin = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Gatchalian Win';");
			while (regionNCRgadon.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRwin.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRwin.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( wintotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRwin.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totaldick = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Gordon Dick';");
			String dicktotal = totaldick.getString("TOTALVOTES");
			totaldick.close();
			
			ResultSet regionNCRdick = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Gordon Dick';");
			while (regionNCRdick.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdick.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdick.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( dicktotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRdick.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalrisa = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Hontiveros Risa';");
			String risatotal = totalrisa.getString("TOTALVOTES");
			totalrisa.close();
			
			ResultSet regionNCRrisa = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Hontiveros Risa';");
			while (regionNCRrisa.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRrisa.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRrisa.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( risatotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRrisa.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalkabalo = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Kabalo Eid';");
			String kabalototal = totalkabalo.getString("TOTALVOTES");
			totalkabalo.close();
			
			ResultSet regionNCRkabalo = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Kabalo Eid';");
			while (regionNCRkabalo.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRkabalo.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRkabalo.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( kabalototal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRkabalo.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalatty = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Kapunan Atty. Lorna';");
			String attytotal = totalatty.getString("TOTALVOTES");
			totalatty.close();
			
			ResultSet regionNCRatty = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Kapunan Atty. Lorna';");
			while (regionNCRatty.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRatty.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRatty.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( attytotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRatty.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalkiram = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Kiram Princess Jacel';");
			String kiramtotal = totalkiram.getString("TOTALVOTES");
			totalkiram.close();
			
			ResultSet regionNCRkiram = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Kiram Princess Jacel';");
			while (regionNCRkiram.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRkiram.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRkiram.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( kiramtotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRkiram.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totallorna = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Lacsamana Alma Moreno';");
			String lornatotal = totallorna.getString("TOTALVOTES");
			totallorna.close();
			
			ResultSet regionNCRlorna= stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Lacsamana Alma Moreno';");
			while (regionNCRlorna.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRlorna.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRlorna.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( lornatotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRlorna.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totallacson = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Lacson Panfilo';");
			String lacsontotal = totallacson.getString("TOTALVOTES");
			totallacson.close();
			
			ResultSet regionNCRlacson= stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Lacson Panfilo';");
			while (regionNCRlacson.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRlacson.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRlacson.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( lacsontotal );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRlacson.close();	
      out.write("\r\n");
      out.write("    \t</tbody>\r\n");
      out.write("    \t<div class=\"page-header\" style=\"padding-left: 5%;\">\r\n");
      out.write("\t\t\t<h1>Region: NCR</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("            <td>\r\n");
      out.write("              <button type=\"button\" class=\"btn\">\r\n");
      out.write("                Click to City Level\r\n");
      out.write("              </button>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr id=\"collapseme\" class=\"collapse out\">\r\n");
      out.write("        \t<td>\r\n");
      out.write("        \t\t<div>\r\n");
      out.write("        \t\t\t");

			ResultSet totalduterte1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Rodrigo Duterte';");
			String dutertetotal1 = totalduterte1.getString("TOTALVOTES");
			totalduterte1.close();
			
			ResultSet regionNCRduterte1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Rodrigo Duterte';");
			while (regionNCRduterte1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRduterte1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRduterte1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( dutertetotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRduterte1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalbinay1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Jejomar Binay';");
			String binaytotal1 = totalbinay1.getString("TOTALVOTES");
			totalbinay1.close();
			
			ResultSet regionNCRbinay1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Jejomar Binay';");
			while (regionNCRbinay1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbinay1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbinay1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( binaytotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRbinay1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalsantiago1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Miriam Santiago';");
			String santiagototal1 = totalsantiago1.getString("TOTALVOTES");
			totalsantiago1.close();
			
			ResultSet regionNCRsantiago1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Miriam Santiago';");
			while (regionNCRsantiago1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRsantiago1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRsantiago1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( santiagototal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRsantiago1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalpoe1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Grace Poe';");
			String poetotal1 = totalpoe1.getString("TOTALVOTES");
			totalpoe1.close();
			
			ResultSet regionNCRpoe1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Grace Poe';");
			while (regionNCRpoe1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRpoe1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRpoe1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( poetotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRpoe1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalroxas1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Mar Roxas';");
			String roxastotal1 = totalroxas1.getString("TOTALVOTES");
			totalroxas1.close();
			
			ResultSet regionNCRroxas1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Mar Roxas';");
			while (regionNCRroxas1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRroxas1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRroxas1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( roxastotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRroxas1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalhonasan1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Gringo Honasan';");
			String honasantotal1 = totalhonasan1.getString("TOTALVOTES");
			totalhonasan1.close();
			
			ResultSet regionNCRhonasan1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Gringo Honasan';");
			while (regionNCRhonasan1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRhonasan1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRhonasan1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( honasantotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRhonasan1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totaltrillanes1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Antonio Trillanes';");
			String trillanestotal1 = totaltrillanes1.getString("TOTALVOTES");
			totaltrillanes1.close();
			
			ResultSet regionNCRtrillanes1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Antonio Trillanes';");
			while (regionNCRtrillanes1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRtrillanes1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRtrillanes1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( trillanestotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRtrillanes1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalescudero1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Francis Escudero';");
			String escuderototal1 = totalescudero1.getString("TOTALVOTES");
			totalescudero1.close();
			
			ResultSet regionNCRescudero1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Francis Escudero';");
			while (regionNCRescudero1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRescudero1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRescudero1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( escuderototal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRescudero1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalrobredo1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Leni Robredo';");
			String robredototal1 = totalrobredo1.getString("TOTALVOTES");
			totalrobredo1.close();
			
			ResultSet regionNCRrobredo1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Leni Robredo';");
			while (regionNCRrobredo1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRrobredo1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRrobredo1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( robredototal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRrobredo1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalmarcos1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Bongbong Marcos';");
			String marcostotal1 = totalmarcos1.getString("TOTALVOTES");
			totalmarcos1.close();
			
			ResultSet regionNCRmarcos1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Bongbong Marcos';");
			while (regionNCRmarcos1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRmarcos1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRmarcos1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( marcostotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRmarcos1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalalan1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Alan Peter Cayetano';");
			String alantotal1 = totalalan1.getString("TOTALVOTES");
			totalalan1.close();
			
			ResultSet regionNCRalan1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Alan Peter Cayetano';");
			while (regionNCRmarcos1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRalan1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRalan1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( alantotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRalan1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalshariff1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Shariff Albani';");
			String sharifftotal1 = totalshariff1.getString("TOTALVOTES");
			totalshariff1.close();
			
			ResultSet regionNCRshariff1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Shariff Albani';");
			while (regionNCRshariff1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRshariff1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRshariff1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( sharifftotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRshariff1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalaldin1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Aldin Ali';");
			String aldintotal1 = totalaldin1.getString("TOTALVOTES");
			totalaldin1.close();
			
			ResultSet regionNCRaldin1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Aldin Ali';");
			while (regionNCRaldin1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRaldin1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRaldin1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( aldintotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRaldin1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalalunan1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Alunan Raffy';");
			String alunantotal1 = totalalunan1.getString("TOTALVOTES");
			totalalunan1.close();
			
			ResultSet regionNCRalunan1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Alunan Raffy';");
			while (regionNCRalunan1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRalunan1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRalunan1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( alunantotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRalunan1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalambolodto1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Ambolodto Ina';");
			String ambolodtototal1 = totalambolodto1.getString("TOTALVOTES");
			totalambolodto1.close();
			
			ResultSet regionNCRambolodto1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Ambolodto Ina';");
			while (regionNCRambolodto1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRambolodto1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRambolodto1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( ambolodtototal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRambolodto1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalarquiza1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Godofredo Arquiza';");
			String arquizatotal1 = totalarquiza1.getString("TOTALVOTES");
			totalarquiza1.close();
			
			ResultSet regionNCRarquiza1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Godofredo Arquiza';");
			while (regionNCRarquiza1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRarquiza1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRarquiza1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( arquizatotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRarquiza1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalbaligod1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Levito Baligod';");
			String baligodtotal1 = totalbaligod1.getString("TOTALVOTES");
			totalbaligod1.close();
			
			ResultSet regionNCRbaligod1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Levito Baligod';");
			while (regionNCRbaligod1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbaligod1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbaligod1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( baligodtotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRbaligod1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalbello1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Bello Walden';");
			String bellototal1 = totalbello1.getString("TOTALVOTES");
			totalbello1.close();
			
			ResultSet regionNCRbello1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Bello Walden';");
			while (regionNCRbello1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbello1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRbello1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( bellototal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRbello1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalcam1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Cam Sandra';");
			String camtotal1 = totalcam1.getString("TOTALVOTES");
			totalcam1.close();
			
			ResultSet regionNCRcam1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Cam Sandra';");
			while (regionNCRcam1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRcam1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRcam1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( camtotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRcam1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalnel1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Chavez Nel';");
			String neltotal1 = totalnel1.getString("TOTALVOTES");
			totalnel1.close();
			
			ResultSet regionNCRnel1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Chavez Nel';");
			while (regionNCRnel1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRnel1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRnel1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( neltotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRnel1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalneri1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Colmenares Neri';");
			String neritotal1 = totalneri1.getString("TOTALVOTES");
			totalneri1.close();
			
			ResultSet regionNCRneri1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Colmenares Neri';");
			while (regionNCRneri1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRneri1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRneri1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( neritotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRneri1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalleila1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='De Lima Leila';");
			String leilatotal1 = totalleila1.getString("TOTALVOTES");
			totalleila1.close();
			
			ResultSet regionNCRleila1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='De Lima Leila';");
			while (regionNCRleila1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRleila1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRleila1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( leilatotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRleila1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalisko1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Domagoso Isko Moreno';");
			String iskototal1 = totalisko1.getString("TOTALVOTES");
			totalisko1.close();
			
			ResultSet regionNCRisko1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Domagoso Isko Moreno';");
			while (regionNCRisko1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRisko1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRisko1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( iskototal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRisko1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totaldorona1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Dorona Ray';");
			String doronatotal1 = totaldorona1.getString("TOTALVOTES");
			totaldorona1.close();
			
			ResultSet regionNCRdorona1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Dorona Ray';");
			while (regionNCRdorona1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdorona1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdorona1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( doronatotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRdorona1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totaldrilon1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Drilon Frank';");
			String drilontotal1 = totaldrilon1.getString("TOTALVOTES");
			totaldrilon1.close();
			
			ResultSet regionNCRdrilon1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Drilon Frank';");
			while (regionNCRdorona1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdrilon1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdrilon1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( drilontotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRdrilon1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalgadon1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Gadon Larry';");
			String gadontotal1 = totalgadon1.getString("TOTALVOTES");
			totalgadon1.close();
			
			ResultSet regionNCRgadon1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Gadon Larry';");
			while (regionNCRgadon1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRgadon1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRgadon1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( gadontotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRgadon1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalwin1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Gatchalian Win';");
			String wintotal1 = totalwin1.getString("TOTALVOTES");
			totalwin1.close();
			
			ResultSet regionNCRwin1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Gatchalian Win';");
			while (regionNCRgadon1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRwin1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRwin1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( wintotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRwin1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totaldick1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Gordon Dick';");
			String dicktotal1 = totaldick1.getString("TOTALVOTES");
			totaldick1.close();
			
			ResultSet regionNCRdick1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Gordon Dick';");
			while (regionNCRdick1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdick1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRdick1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( dicktotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRdick1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalrisa1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Hontiveros Risa';");
			String risatotal1 = totalrisa1.getString("TOTALVOTES");
			totalrisa1.close();
			
			ResultSet regionNCRrisa1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Hontiveros Risa';");
			while (regionNCRrisa1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRrisa1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRrisa1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( risatotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRrisa1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalkabalo1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Kabalo Eid';");
			String kabalototal1 = totalkabalo1.getString("TOTALVOTES");
			totalkabalo1.close();
			
			ResultSet regionNCRkabalo1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Kabalo Eid';");
			while (regionNCRkabalo1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRkabalo1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRkabalo1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( kabalototal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRkabalo1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalatty1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Kapunan Atty. Lorna';");
			String attytotal1 = totalatty1.getString("TOTALVOTES");
			totalatty1.close();
			
			ResultSet regionNCRatty1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Kapunan Atty. Lorna';");
			while (regionNCRatty1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRatty1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRatty1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( attytotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRatty1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totalkiram1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Kiram Princess Jacel';");
			String kiramtotal1 = totalkiram1.getString("TOTALVOTES");
			totalkiram1.close();
			
			ResultSet regionNCRkiram1 = stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Kiram Princess Jacel';");
			while (regionNCRkiram1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRkiram1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRkiram1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( kiramtotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRkiram1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totallorna1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Lacsamana Alma Moreno';");
			String lornatotal1 = totallorna1.getString("TOTALVOTES");
			totallorna1.close();
			
			ResultSet regionNCRlorna1= stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Lacsamana Alma Moreno';");
			while (regionNCRlorna1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRlorna1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRlorna1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( lornatotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRlorna1.close();	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			ResultSet totallacson1 = stat.executeQuery("SELECT SUM(vote) as 'TOTALVOTES' FROM tapat WHERE name='Lacson Panfilo';");
			String lacsontotal1 = totallacson1.getString("TOTALVOTES");
			totallacson1.close();
			
			ResultSet regionNCRlacson1= stat.executeQuery("SELECT distinct candidacy,name FROM tapat WHERE region='NCR' and name='Lacson Panfilo';");
			while (regionNCRlacson1.next()) {	    
			    
      out.write("\r\n");
      out.write("\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRlacson1.getString("candidacy") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( regionNCRlacson1.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t\t<td>");
      out.print( lacsontotal1 );
      out.write("</td>\r\n");
      out.write("\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t    ");

			}
			regionNCRlacson1.close();	
      out.write("\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("        \t</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
